### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by whisperzqh** [FasterDecoding/REST#25]
Hi, when I try to use deepseek-coder-6.7b-base to construct the datastore for code-related tasks, I also encounter the `segmentation fault (core dumped)` as mentioned in [issue #19 ](https://github.com/FasterDecoding/REST/issues/19). However, the vocab size of deepseek-coder-6.7b-base is 32000, which is smaller than 65535. I have also tried the solution mentioned there, but it didn't fix the bug. How can I resolve this problem? Thank you!

**Comment by zhenyuhe00** [comment]
Hi, 
I assume the issue lies in the [following code](https://github.com/FasterDecoding/REST/blob/main/datastore/get_datastore_code.py#L44):
`writer = draftretriever.Writer(
    index_file_path=datastore_path,
    max_chunk_len=512 * 1024 * 1024,
    vocab_size=tokenizer.vocab_size,
)`
Here, tokenizer.vocab_size is set to 32,000 for deepseek-coder-6.7b-base. However, the actual vocab_size for deepseek-coder-6.7b-base is 32,000 plus the number of added_tokens, which totals 32,021.

I've change the code `vocab_size=tokenizer.vocab_size` to `vocab_size=tokenizer.vocab_size+len(tokenizer.get_added_vocab())`. Sorry for the bug.

**Comment by whisperzqh** [comment]
Thanks!!
