### ISSUE TITLE
Questions about past_key_values_data

### ISSUE THREAD

**Issue by reflectionie** [FasterDecoding/REST#6]
Hi, thank you for your wonderful work! Can I ask, why did you update the past_key_values_data variable in the code? 
The link is here: https://github.com/FasterDecoding/REST/blob/5b119c1d2c318549bf6ef45aaba126b9e7d59529/rest/model/utils.py#L325
This variable doesn't seem to be involved when using KVcache, but you still create and update it when decoding.

**Comment by zhenyuhe00** [comment]
Thanks for the question.  
https://github.com/FasterDecoding/REST/blob/5b119c1d2c318549bf6ef45aaba126b9e7d59529/rest/model/utils.py#L325-L329
In the code above, tgt is used to update dst. Since dst is a slice view of the original past_key_values_data, the past_key_values_data is also updated. 

https://github.com/FasterDecoding/REST/blob/5b119c1d2c318549bf6ef45aaba126b9e7d59529/rest/model/kv_cache.py#L92-L100
The past_key_values_data is created in advance to accommodate the max sequence length for faster memory management (static cache). However, you can also change it to [dynamic cache](https://github.com/huggingface/transformers/blob/main/src/transformers/cache_utils.py#L76), which appends new pask_key_value on the fly.

**Comment by reflectionie** [comment]
Thanks for the explanation, I totally understand now!
